name: aksyn_monitor
description: Real-time audio stream monitor for Aksyn Challenge

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # WebSocket
  web_socket_channel: ^2.4.0

  http: ^1.2.0          
  audioplayers: ^6.0.0

  # Charts for latency graph
  fl_chart: ^0.68.0

  # Google Fonts
  google_fonts: ^6.1.0

  # State management
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
